bazel_dep(name = "contrib_rules_jvm", version = "0.32.0")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_java", version = "9.6.1")
bazel_dep(name = "rules_jvm_external", version = "6.10")

# FIXME: Workaround for "The CcInfo symbol has been removed"
bazel_dep(name = "rules_android", version = "0.7.1")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "ch.qos.logback:logback-classic:1.5.22",
        "com.google.auto.value:auto-value-annotations:1.11.1",
        "com.google.auto.value:auto-value:1.11.1",
        "com.google.code.gson:gson:2.13.2",
        "com.google.guava:guava:33.5.0-jre",
        "com.google.truth:truth:1.4.5",
        "net.java.dev.jna:jna:5.18.1",
        "org.junit.jupiter:junit-jupiter-api:6.0.2",
        "org.junit.jupiter:junit-jupiter-engine:6.0.2",
        "org.junit.jupiter:junit-jupiter-params:6.0.2",
        "org.junit.platform:junit-platform-launcher:6.0.2",
        "org.junit.platform:junit-platform-reporting:6.0.2",
        "org.mockito:mockito-core:5.23.0",
        "org.mockito:mockito-junit-jupiter:5.23.0",
        "org.slf4j:slf4j-api:2.0.17",
    ],
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
use_repo(maven, "maven")
