package com.zacharyhirsch.moldygameboy.emulator.cpu;

import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.AbstractInstruction1;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Adc;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Add;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.And;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Bit;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Call;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Callcc;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Ccf;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Cp;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Cpl;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Daa;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Dec;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Di;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Ei;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Halt;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Inc;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Instruction;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Jp;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Jpcc;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Jr;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Jrcc;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Ld;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Mem;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Nop;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Or;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Pop;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Push;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Res;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Ret;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Retcc;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Reti;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Rl;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Rla;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Rlc;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Rlca;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Rr;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Rra;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Rrc;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Rrca;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Rst;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Sbc;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Scf;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Set;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Sla;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Sra;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Srl;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Stop;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Sub;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Swap;
import com.zacharyhirsch.moldygameboy.emulator.cpu.instructions.Xor;
import com.zacharyhirsch.moldygameboy.emulator.cpu.registers.Registers;

final class CpuDecoder {

  private final Registers registers;

  private boolean prefixed = false;

  CpuDecoder(Registers registers) {
    this.registers = registers;
  }

  private Instruction prefix() {
    prefixed = true;
    return new AbstractInstruction1() {
      @Override
      protected Mem execute0() {
        return Mem.read(registers.pc().getAndIncrement(), registers.ir()::set);
      }
    };
  }

  Instruction decode() {
    if (prefixed) {
      prefixed = false;
      return decodePrefixed();
    }
    return switch (Byte.toUnsignedInt(registers.ir().get())) {
      case 0x00 -> new Nop(registers);
      case 0x01 -> new Ld.RegisterImmediate16(registers, registers.bc());
      case 0x02 -> new Ld.IndirectRegister(registers, registers.a(), registers.bc());
      case 0x03 -> new Inc.R16(registers, registers.bc());
      case 0x04 -> new Inc.R8(registers, registers.b());
      case 0x05 -> new Dec.R8(registers, registers.b());
      case 0x06 -> new Ld.RegisterImmediate8(registers, registers.b());
      case 0x07 -> new Rlca(registers);
      case 0x08 -> new Ld.DirectStackPointer(registers);
      case 0x09 -> new Add.Immediate16(registers, registers.bc());
      case 0x0a -> new Ld.AccumulatorIndirect(registers, registers.bc());
      case 0x0b -> new Dec.R16(registers, registers.bc());
      case 0x0c -> new Inc.R8(registers, registers.c());
      case 0x0d -> new Dec.R8(registers, registers.c());
      case 0x0e -> new Ld.RegisterImmediate8(registers, registers.c());
      case 0x0f -> new Rrca(registers);
      case 0x10 -> new Stop(registers);
      case 0x11 -> new Ld.RegisterImmediate16(registers, registers.de());
      case 0x12 -> new Ld.IndirectRegister(registers, registers.a(), registers.de());
      case 0x13 -> new Inc.R16(registers, registers.de());
      case 0x14 -> new Inc.R8(registers, registers.d());
      case 0x15 -> new Dec.R8(registers, registers.d());
      case 0x16 -> new Ld.RegisterImmediate8(registers, registers.d());
      case 0x17 -> new Rla(registers);
      case 0x18 -> new Jr(registers);
      case 0x19 -> new Add.Immediate16(registers, registers.de());
      case 0x1a -> new Ld.AccumulatorIndirect(registers, registers.de());
      case 0x1b -> new Dec.R16(registers, registers.de());
      case 0x1c -> new Inc.R8(registers, registers.e());
      case 0x1d -> new Dec.R8(registers, registers.e());
      case 0x1e -> new Ld.RegisterImmediate8(registers, registers.e());
      case 0x1f -> new Rra(registers);
      case 0x20 -> new Jrcc(registers, flags -> !flags.z().get());
      case 0x21 -> new Ld.RegisterImmediate16(registers, registers.hl());
      case 0x22 -> new Ld.IndirectIncrementAccumulator(registers);
      case 0x23 -> new Inc.R16(registers, registers.hl());
      case 0x24 -> new Inc.R8(registers, registers.h());
      case 0x25 -> new Dec.R8(registers, registers.h());
      case 0x26 -> new Ld.RegisterImmediate8(registers, registers.h());
      case 0x27 -> new Daa(registers);
      case 0x28 -> new Jrcc(registers, flags -> flags.z().get());
      case 0x29 -> new Add.Immediate16(registers, registers.hl());
      case 0x2a -> new Ld.RegisterIndirectIncrement(registers, registers.a());
      case 0x2b -> new Dec.R16(registers, registers.hl());
      case 0x2c -> new Inc.R8(registers, registers.l());
      case 0x2d -> new Dec.R8(registers, registers.l());
      case 0x2e -> new Ld.RegisterImmediate8(registers, registers.l());
      case 0x2f -> new Cpl(registers);
      case 0x30 -> new Jrcc(registers, flags -> !flags.c().get());
      case 0x31 -> new Ld.RegisterImmediate16(registers, registers.sp());
      case 0x32 -> new Ld.IndirectDecrementAccumulator(registers);
      case 0x33 -> new Inc.R16(registers, registers.sp());
      case 0x34 -> new Inc.Indirect(registers);
      case 0x35 -> new Dec.Indirect(registers);
      case 0x36 -> new Ld.ImmediateIndirect(registers);
      case 0x37 -> new Scf(registers);
      case 0x38 -> new Jrcc(registers, flags -> flags.c().get());
      case 0x39 -> new Add.Immediate16(registers, registers.sp());
      case 0x3a -> new Ld.AccumulatorIndirectDecrement(registers, registers.hl());
      case 0x3b -> new Dec.R16(registers, registers.sp());
      case 0x3c -> new Inc.R8(registers, registers.a());
      case 0x3d -> new Dec.R8(registers, registers.a());
      case 0x3e -> new Ld.RegisterImmediate8(registers, registers.a());
      case 0x3f -> new Ccf(registers);
      case 0x40 -> new Ld.RegisterRegister(registers, registers.b(), registers.b());
      case 0x41 -> new Ld.RegisterRegister(registers, registers.c(), registers.b());
      case 0x42 -> new Ld.RegisterRegister(registers, registers.d(), registers.b());
      case 0x43 -> new Ld.RegisterRegister(registers, registers.e(), registers.b());
      case 0x44 -> new Ld.RegisterRegister(registers, registers.h(), registers.b());
      case 0x45 -> new Ld.RegisterRegister(registers, registers.l(), registers.b());
      case 0x46 -> new Ld.RegisterIndirect(registers, registers.b());
      case 0x47 -> new Ld.RegisterRegister(registers, registers.a(), registers.b());
      case 0x48 -> new Ld.RegisterRegister(registers, registers.b(), registers.c());
      case 0x49 -> new Ld.RegisterRegister(registers, registers.c(), registers.c());
      case 0x4a -> new Ld.RegisterRegister(registers, registers.d(), registers.c());
      case 0x4b -> new Ld.RegisterRegister(registers, registers.e(), registers.c());
      case 0x4c -> new Ld.RegisterRegister(registers, registers.h(), registers.c());
      case 0x4d -> new Ld.RegisterRegister(registers, registers.l(), registers.c());
      case 0x4e -> new Ld.RegisterIndirect(registers, registers.c());
      case 0x4f -> new Ld.RegisterRegister(registers, registers.a(), registers.c());
      case 0x50 -> new Ld.RegisterRegister(registers, registers.b(), registers.d());
      case 0x51 -> new Ld.RegisterRegister(registers, registers.c(), registers.d());
      case 0x52 -> new Ld.RegisterRegister(registers, registers.d(), registers.d());
      case 0x53 -> new Ld.RegisterRegister(registers, registers.e(), registers.d());
      case 0x54 -> new Ld.RegisterRegister(registers, registers.h(), registers.d());
      case 0x55 -> new Ld.RegisterRegister(registers, registers.l(), registers.d());
      case 0x56 -> new Ld.RegisterIndirect(registers, registers.d());
      case 0x57 -> new Ld.RegisterRegister(registers, registers.a(), registers.d());
      case 0x58 -> new Ld.RegisterRegister(registers, registers.b(), registers.e());
      case 0x59 -> new Ld.RegisterRegister(registers, registers.c(), registers.e());
      case 0x5a -> new Ld.RegisterRegister(registers, registers.d(), registers.e());
      case 0x5b -> new Ld.RegisterRegister(registers, registers.e(), registers.e());
      case 0x5c -> new Ld.RegisterRegister(registers, registers.h(), registers.e());
      case 0x5d -> new Ld.RegisterRegister(registers, registers.l(), registers.e());
      case 0x5e -> new Ld.RegisterIndirect(registers, registers.e());
      case 0x5f -> new Ld.RegisterRegister(registers, registers.a(), registers.e());
      case 0x60 -> new Ld.RegisterRegister(registers, registers.b(), registers.h());
      case 0x61 -> new Ld.RegisterRegister(registers, registers.c(), registers.h());
      case 0x62 -> new Ld.RegisterRegister(registers, registers.d(), registers.h());
      case 0x63 -> new Ld.RegisterRegister(registers, registers.e(), registers.h());
      case 0x64 -> new Ld.RegisterRegister(registers, registers.h(), registers.h());
      case 0x65 -> new Ld.RegisterRegister(registers, registers.l(), registers.h());
      case 0x66 -> new Ld.RegisterIndirect(registers, registers.h());
      case 0x67 -> new Ld.RegisterRegister(registers, registers.a(), registers.h());
      case 0x68 -> new Ld.RegisterRegister(registers, registers.b(), registers.l());
      case 0x69 -> new Ld.RegisterRegister(registers, registers.c(), registers.l());
      case 0x6a -> new Ld.RegisterRegister(registers, registers.d(), registers.l());
      case 0x6b -> new Ld.RegisterRegister(registers, registers.e(), registers.l());
      case 0x6c -> new Ld.RegisterRegister(registers, registers.h(), registers.l());
      case 0x6d -> new Ld.RegisterRegister(registers, registers.l(), registers.l());
      case 0x6e -> new Ld.RegisterIndirect(registers, registers.l());
      case 0x6f -> new Ld.RegisterRegister(registers, registers.a(), registers.l());
      case 0x70 -> new Ld.IndirectRegister(registers, registers.b(), registers.hl());
      case 0x71 -> new Ld.IndirectRegister(registers, registers.c(), registers.hl());
      case 0x72 -> new Ld.IndirectRegister(registers, registers.d(), registers.hl());
      case 0x73 -> new Ld.IndirectRegister(registers, registers.e(), registers.hl());
      case 0x74 -> new Ld.IndirectRegister(registers, registers.h(), registers.hl());
      case 0x75 -> new Ld.IndirectRegister(registers, registers.l(), registers.hl());
      case 0x76 -> new Halt(registers);
      case 0x77 -> new Ld.IndirectRegister(registers, registers.a(), registers.hl());
      case 0x78 -> new Ld.RegisterRegister(registers, registers.b(), registers.a());
      case 0x79 -> new Ld.RegisterRegister(registers, registers.c(), registers.a());
      case 0x7a -> new Ld.RegisterRegister(registers, registers.d(), registers.a());
      case 0x7b -> new Ld.RegisterRegister(registers, registers.e(), registers.a());
      case 0x7c -> new Ld.RegisterRegister(registers, registers.h(), registers.a());
      case 0x7d -> new Ld.RegisterRegister(registers, registers.l(), registers.a());
      case 0x7e -> new Ld.RegisterIndirect(registers, registers.a());
      case 0x7f -> new Ld.RegisterRegister(registers, registers.a(), registers.a());
      case 0x80 -> new Add.Register(registers, registers.b());
      case 0x81 -> new Add.Register(registers, registers.c());
      case 0x82 -> new Add.Register(registers, registers.d());
      case 0x83 -> new Add.Register(registers, registers.e());
      case 0x84 -> new Add.Register(registers, registers.h());
      case 0x85 -> new Add.Register(registers, registers.l());
      case 0x86 -> new Add.Indirect(registers);
      case 0x87 -> new Add.Register(registers, registers.a());
      case 0x88 -> new Adc.Register(registers, registers.b());
      case 0x89 -> new Adc.Register(registers, registers.c());
      case 0x8a -> new Adc.Register(registers, registers.d());
      case 0x8b -> new Adc.Register(registers, registers.e());
      case 0x8c -> new Adc.Register(registers, registers.h());
      case 0x8d -> new Adc.Register(registers, registers.l());
      case 0x8e -> new Adc.Indirect(registers);
      case 0x8f -> new Adc.Register(registers, registers.a());
      case 0x90 -> new Sub.Register(registers, registers.b());
      case 0x91 -> new Sub.Register(registers, registers.c());
      case 0x92 -> new Sub.Register(registers, registers.d());
      case 0x93 -> new Sub.Register(registers, registers.e());
      case 0x94 -> new Sub.Register(registers, registers.h());
      case 0x95 -> new Sub.Register(registers, registers.l());
      case 0x96 -> new Sub.Indirect(registers);
      case 0x97 -> new Sub.Register(registers, registers.a());
      case 0x98 -> new Sbc.Register(registers, registers.b());
      case 0x99 -> new Sbc.Register(registers, registers.c());
      case 0x9a -> new Sbc.Register(registers, registers.d());
      case 0x9b -> new Sbc.Register(registers, registers.e());
      case 0x9c -> new Sbc.Register(registers, registers.h());
      case 0x9d -> new Sbc.Register(registers, registers.l());
      case 0x9e -> new Sbc.Indirect(registers);
      case 0x9f -> new Sbc.Register(registers, registers.a());
      case 0xa0 -> new And.Register(registers, registers.b());
      case 0xa1 -> new And.Register(registers, registers.c());
      case 0xa2 -> new And.Register(registers, registers.d());
      case 0xa3 -> new And.Register(registers, registers.e());
      case 0xa4 -> new And.Register(registers, registers.h());
      case 0xa5 -> new And.Register(registers, registers.l());
      case 0xa6 -> new And.Indirect(registers);
      case 0xa7 -> new And.Register(registers, registers.a());
      case 0xa8 -> new Xor.Register(registers, registers.b());
      case 0xa9 -> new Xor.Register(registers, registers.c());
      case 0xaa -> new Xor.Register(registers, registers.d());
      case 0xab -> new Xor.Register(registers, registers.e());
      case 0xac -> new Xor.Register(registers, registers.h());
      case 0xad -> new Xor.Register(registers, registers.l());
      case 0xae -> new Xor.Indirect(registers);
      case 0xaf -> new Xor.Register(registers, registers.a());
      case 0xb0 -> new Or.Register(registers, registers.b());
      case 0xb1 -> new Or.Register(registers, registers.c());
      case 0xb2 -> new Or.Register(registers, registers.d());
      case 0xb3 -> new Or.Register(registers, registers.e());
      case 0xb4 -> new Or.Register(registers, registers.h());
      case 0xb5 -> new Or.Register(registers, registers.l());
      case 0xb6 -> new Or.Indirect(registers);
      case 0xb7 -> new Or.Register(registers, registers.a());
      case 0xb8 -> new Cp.Register(registers, registers.b());
      case 0xb9 -> new Cp.Register(registers, registers.c());
      case 0xba -> new Cp.Register(registers, registers.d());
      case 0xbb -> new Cp.Register(registers, registers.e());
      case 0xbc -> new Cp.Register(registers, registers.h());
      case 0xbd -> new Cp.Register(registers, registers.l());
      case 0xbe -> new Cp.Indirect(registers);
      case 0xbf -> new Cp.Register(registers, registers.a());
      case 0xc0 -> new Retcc(registers, flags -> !flags.z().get());
      case 0xc1 -> new Pop(registers, registers.bc());
      case 0xc2 -> new Jpcc.Immediate(registers, flags -> !flags.z().get());
      case 0xc3 -> new Jp.Immediate(registers);
      case 0xc4 -> new Callcc(registers, flags -> !flags.z().get());
      case 0xc5 -> new Push(registers, registers.bc());
      case 0xc6 -> new Add.Immediate8(registers);
      case 0xc7 -> new Rst(registers, (short) 0x00);
      case 0xc8 -> new Retcc(registers, flags -> flags.z().get());
      case 0xc9 -> new Ret(registers);
      case 0xca -> new Jpcc.Immediate(registers, flags -> flags.z().get());
      case 0xcb -> prefix();
      case 0xcc -> new Callcc(registers, flags -> flags.z().get());
      case 0xcd -> new Call(registers);
      case 0xce -> new Adc.Immediate(registers);
      case 0xcf -> new Rst(registers, (short) 0x08);
      case 0xd0 -> new Retcc(registers, flags -> !flags.c().get());
      case 0xd1 -> new Pop(registers, registers.de());
      case 0xd2 -> new Jpcc.Immediate(registers, flags -> !flags.c().get());
      // case 0xd3 -> null; // illegal
      case 0xd4 -> new Callcc(registers, flags -> !flags.c().get());
      case 0xd5 -> new Push(registers, registers.de());
      case 0xd6 -> new Sub.Immediate(registers);
      case 0xd7 -> new Rst(registers, (short) 0x10);
      case 0xd8 -> new Retcc(registers, flags -> flags.c().get());
      case 0xd9 -> new Reti(registers);
      case 0xda -> new Jpcc.Immediate(registers, flags -> flags.c().get());
      // case 0xdb -> null; // illegal
      case 0xdc -> new Callcc(registers, flags -> flags.c().get());
      // case 0xdd -> null; // illegal
      case 0xde -> new Sbc.Immediate(registers);
      case 0xdf -> new Rst(registers, (short) 0x18);
      case 0xe0 -> new Ld.DirectHiAccumulator(registers);
      case 0xe1 -> new Pop(registers, registers.hl());
      case 0xe2 -> new Ld.IndirectHiAccumulator(registers, registers.c());
      // case 0xe3 -> null; // illegal
      // case 0xe4 -> null; // illegal
      case 0xe5 -> new Push(registers, registers.hl());
      case 0xe6 -> new And.Immediate(registers);
      case 0xe7 -> new Rst(registers, (short) 0x20);
      case 0xe8 -> new Add.StackOffset(registers);
      case 0xe9 -> new Jp.Register(registers);
      case 0xea -> new Ld.DirectAccumulator(registers);
      // case 0xeb -> null; // illegal
      // case 0xec -> null; // illegal
      // case 0xed -> null; // illegal
      case 0xee -> new Xor.Immediate(registers);
      case 0xef -> new Rst(registers, (short) 0x28);
      case 0xf0 -> new Ld.AccumulatorDirectHi(registers);
      case 0xf1 -> new Pop(registers, registers.af());
      case 0xf2 -> new Ld.AccumulatorIndirectHi(registers, registers.c());
      case 0xf3 -> new Di(registers);
      // case 0xf4 -> null; // illegal
      case 0xf5 -> new Push(registers, registers.af());
      case 0xf6 -> new Or.Immediate(registers);
      case 0xf7 -> new Rst(registers, (short) 0x30);
      case 0xf8 -> new Ld.StackOffset(registers);
      case 0xf9 -> new Ld.RegisterRegister16(registers, registers.hl(), registers.sp());
      case 0xfa -> new Ld.AccumulatorDirect(registers);
      case 0xfb -> new Ei(registers);
      // case 0xfc -> null; // illegal
      // case 0xfd -> null; // illegal
      case 0xfe -> new Cp.Immediate(registers);
      case 0xff -> new Rst(registers, (short) 0x38);
      default -> throw new InvalidOpcodeError(registers.ir().get());
    };
  }

  private Instruction decodePrefixed() {
    return switch (Byte.toUnsignedInt(registers.ir().get())) {
      case 0x00 -> new Rlc.Register(registers, registers.b());
      case 0x01 -> new Rlc.Register(registers, registers.c());
      case 0x02 -> new Rlc.Register(registers, registers.d());
      case 0x03 -> new Rlc.Register(registers, registers.e());
      case 0x04 -> new Rlc.Register(registers, registers.h());
      case 0x05 -> new Rlc.Register(registers, registers.l());
      case 0x06 -> new Rlc.Indirect(registers);
      case 0x07 -> new Rlc.Register(registers, registers.a());
      case 0x08 -> new Rrc.Register(registers, registers.b());
      case 0x09 -> new Rrc.Register(registers, registers.c());
      case 0x0a -> new Rrc.Register(registers, registers.d());
      case 0x0b -> new Rrc.Register(registers, registers.e());
      case 0x0c -> new Rrc.Register(registers, registers.h());
      case 0x0d -> new Rrc.Register(registers, registers.l());
      case 0x0e -> new Rrc.Indirect(registers);
      case 0x0f -> new Rrc.Register(registers, registers.a());
      case 0x10 -> new Rl.Register(registers, registers.b());
      case 0x11 -> new Rl.Register(registers, registers.c());
      case 0x12 -> new Rl.Register(registers, registers.d());
      case 0x13 -> new Rl.Register(registers, registers.e());
      case 0x14 -> new Rl.Register(registers, registers.h());
      case 0x15 -> new Rl.Register(registers, registers.l());
      case 0x16 -> new Rl.Indirect(registers);
      case 0x17 -> new Rl.Register(registers, registers.a());
      case 0x18 -> new Rr.Register(registers, registers.b());
      case 0x19 -> new Rr.Register(registers, registers.c());
      case 0x1a -> new Rr.Register(registers, registers.d());
      case 0x1b -> new Rr.Register(registers, registers.e());
      case 0x1c -> new Rr.Register(registers, registers.h());
      case 0x1d -> new Rr.Register(registers, registers.l());
      case 0x1e -> new Rr.Indirect(registers);
      case 0x1f -> new Rr.Register(registers, registers.a());
      case 0x20 -> new Sla.Register(registers, registers.b());
      case 0x21 -> new Sla.Register(registers, registers.c());
      case 0x22 -> new Sla.Register(registers, registers.d());
      case 0x23 -> new Sla.Register(registers, registers.e());
      case 0x24 -> new Sla.Register(registers, registers.h());
      case 0x25 -> new Sla.Register(registers, registers.l());
      case 0x26 -> new Sla.Indirect(registers);
      case 0x27 -> new Sla.Register(registers, registers.a());
      case 0x28 -> new Sra.Register(registers, registers.b());
      case 0x29 -> new Sra.Register(registers, registers.c());
      case 0x2a -> new Sra.Register(registers, registers.d());
      case 0x2b -> new Sra.Register(registers, registers.e());
      case 0x2c -> new Sra.Register(registers, registers.h());
      case 0x2d -> new Sra.Register(registers, registers.l());
      case 0x2e -> new Sra.Indirect(registers);
      case 0x2f -> new Sra.Register(registers, registers.a());
      case 0x30 -> new Swap.Register(registers, registers.b());
      case 0x31 -> new Swap.Register(registers, registers.c());
      case 0x32 -> new Swap.Register(registers, registers.d());
      case 0x33 -> new Swap.Register(registers, registers.e());
      case 0x34 -> new Swap.Register(registers, registers.h());
      case 0x35 -> new Swap.Register(registers, registers.l());
      case 0x36 -> new Swap.Indirect(registers);
      case 0x37 -> new Swap.Register(registers, registers.a());
      case 0x38 -> new Srl.Register(registers, registers.b());
      case 0x39 -> new Srl.Register(registers, registers.c());
      case 0x3a -> new Srl.Register(registers, registers.d());
      case 0x3b -> new Srl.Register(registers, registers.e());
      case 0x3c -> new Srl.Register(registers, registers.h());
      case 0x3d -> new Srl.Register(registers, registers.l());
      case 0x3e -> new Srl.Indirect(registers);
      case 0x3f -> new Srl.Register(registers, registers.a());
      case 0x40 -> new Bit.Register(registers, registers.b(), 0);
      case 0x41 -> new Bit.Register(registers, registers.c(), 0);
      case 0x42 -> new Bit.Register(registers, registers.d(), 0);
      case 0x43 -> new Bit.Register(registers, registers.e(), 0);
      case 0x44 -> new Bit.Register(registers, registers.h(), 0);
      case 0x45 -> new Bit.Register(registers, registers.l(), 0);
      case 0x46 -> new Bit.Indirect(registers, 0);
      case 0x47 -> new Bit.Register(registers, registers.a(), 0);
      case 0x48 -> new Bit.Register(registers, registers.b(), 1);
      case 0x49 -> new Bit.Register(registers, registers.c(), 1);
      case 0x4a -> new Bit.Register(registers, registers.d(), 1);
      case 0x4b -> new Bit.Register(registers, registers.e(), 1);
      case 0x4c -> new Bit.Register(registers, registers.h(), 1);
      case 0x4d -> new Bit.Register(registers, registers.l(), 1);
      case 0x4e -> new Bit.Indirect(registers, 1);
      case 0x4f -> new Bit.Register(registers, registers.a(), 1);
      case 0x50 -> new Bit.Register(registers, registers.b(), 2);
      case 0x51 -> new Bit.Register(registers, registers.c(), 2);
      case 0x52 -> new Bit.Register(registers, registers.d(), 2);
      case 0x53 -> new Bit.Register(registers, registers.e(), 2);
      case 0x54 -> new Bit.Register(registers, registers.h(), 2);
      case 0x55 -> new Bit.Register(registers, registers.l(), 2);
      case 0x56 -> new Bit.Indirect(registers, 2);
      case 0x57 -> new Bit.Register(registers, registers.a(), 2);
      case 0x58 -> new Bit.Register(registers, registers.b(), 3);
      case 0x59 -> new Bit.Register(registers, registers.c(), 3);
      case 0x5a -> new Bit.Register(registers, registers.d(), 3);
      case 0x5b -> new Bit.Register(registers, registers.e(), 3);
      case 0x5c -> new Bit.Register(registers, registers.h(), 3);
      case 0x5d -> new Bit.Register(registers, registers.l(), 3);
      case 0x5e -> new Bit.Indirect(registers, 3);
      case 0x5f -> new Bit.Register(registers, registers.a(), 3);
      case 0x60 -> new Bit.Register(registers, registers.b(), 4);
      case 0x61 -> new Bit.Register(registers, registers.c(), 4);
      case 0x62 -> new Bit.Register(registers, registers.d(), 4);
      case 0x63 -> new Bit.Register(registers, registers.e(), 4);
      case 0x64 -> new Bit.Register(registers, registers.h(), 4);
      case 0x65 -> new Bit.Register(registers, registers.l(), 4);
      case 0x66 -> new Bit.Indirect(registers, 4);
      case 0x67 -> new Bit.Register(registers, registers.a(), 4);
      case 0x68 -> new Bit.Register(registers, registers.b(), 5);
      case 0x69 -> new Bit.Register(registers, registers.c(), 5);
      case 0x6a -> new Bit.Register(registers, registers.d(), 5);
      case 0x6b -> new Bit.Register(registers, registers.e(), 5);
      case 0x6c -> new Bit.Register(registers, registers.h(), 5);
      case 0x6d -> new Bit.Register(registers, registers.l(), 5);
      case 0x6e -> new Bit.Indirect(registers, 5);
      case 0x6f -> new Bit.Register(registers, registers.a(), 5);
      case 0x70 -> new Bit.Register(registers, registers.b(), 6);
      case 0x71 -> new Bit.Register(registers, registers.c(), 6);
      case 0x72 -> new Bit.Register(registers, registers.d(), 6);
      case 0x73 -> new Bit.Register(registers, registers.e(), 6);
      case 0x74 -> new Bit.Register(registers, registers.h(), 6);
      case 0x75 -> new Bit.Register(registers, registers.l(), 6);
      case 0x76 -> new Bit.Indirect(registers, 6);
      case 0x77 -> new Bit.Register(registers, registers.a(), 6);
      case 0x78 -> new Bit.Register(registers, registers.b(), 7);
      case 0x79 -> new Bit.Register(registers, registers.c(), 7);
      case 0x7a -> new Bit.Register(registers, registers.d(), 7);
      case 0x7b -> new Bit.Register(registers, registers.e(), 7);
      case 0x7c -> new Bit.Register(registers, registers.h(), 7);
      case 0x7d -> new Bit.Register(registers, registers.l(), 7);
      case 0x7e -> new Bit.Indirect(registers, 7);
      case 0x7f -> new Bit.Register(registers, registers.a(), 7);
      case 0x80 -> new Res.Register(registers, registers.b(), 0);
      case 0x81 -> new Res.Register(registers, registers.c(), 0);
      case 0x82 -> new Res.Register(registers, registers.d(), 0);
      case 0x83 -> new Res.Register(registers, registers.e(), 0);
      case 0x84 -> new Res.Register(registers, registers.h(), 0);
      case 0x85 -> new Res.Register(registers, registers.l(), 0);
      case 0x86 -> new Res.Indirect(registers, 0);
      case 0x87 -> new Res.Register(registers, registers.a(), 0);
      case 0x88 -> new Res.Register(registers, registers.b(), 1);
      case 0x89 -> new Res.Register(registers, registers.c(), 1);
      case 0x8a -> new Res.Register(registers, registers.d(), 1);
      case 0x8b -> new Res.Register(registers, registers.e(), 1);
      case 0x8c -> new Res.Register(registers, registers.h(), 1);
      case 0x8d -> new Res.Register(registers, registers.l(), 1);
      case 0x8e -> new Res.Indirect(registers, 1);
      case 0x8f -> new Res.Register(registers, registers.a(), 1);
      case 0x90 -> new Res.Register(registers, registers.b(), 2);
      case 0x91 -> new Res.Register(registers, registers.c(), 2);
      case 0x92 -> new Res.Register(registers, registers.d(), 2);
      case 0x93 -> new Res.Register(registers, registers.e(), 2);
      case 0x94 -> new Res.Register(registers, registers.h(), 2);
      case 0x95 -> new Res.Register(registers, registers.l(), 2);
      case 0x96 -> new Res.Indirect(registers, 2);
      case 0x97 -> new Res.Register(registers, registers.a(), 2);
      case 0x98 -> new Res.Register(registers, registers.b(), 3);
      case 0x99 -> new Res.Register(registers, registers.c(), 3);
      case 0x9a -> new Res.Register(registers, registers.d(), 3);
      case 0x9b -> new Res.Register(registers, registers.e(), 3);
      case 0x9c -> new Res.Register(registers, registers.h(), 3);
      case 0x9d -> new Res.Register(registers, registers.l(), 3);
      case 0x9e -> new Res.Indirect(registers, 3);
      case 0x9f -> new Res.Register(registers, registers.a(), 3);
      case 0xa0 -> new Res.Register(registers, registers.b(), 4);
      case 0xa1 -> new Res.Register(registers, registers.c(), 4);
      case 0xa2 -> new Res.Register(registers, registers.d(), 4);
      case 0xa3 -> new Res.Register(registers, registers.e(), 4);
      case 0xa4 -> new Res.Register(registers, registers.h(), 4);
      case 0xa5 -> new Res.Register(registers, registers.l(), 4);
      case 0xa6 -> new Res.Indirect(registers, 4);
      case 0xa7 -> new Res.Register(registers, registers.a(), 4);
      case 0xa8 -> new Res.Register(registers, registers.b(), 5);
      case 0xa9 -> new Res.Register(registers, registers.c(), 5);
      case 0xaa -> new Res.Register(registers, registers.d(), 5);
      case 0xab -> new Res.Register(registers, registers.e(), 5);
      case 0xac -> new Res.Register(registers, registers.h(), 5);
      case 0xad -> new Res.Register(registers, registers.l(), 5);
      case 0xae -> new Res.Indirect(registers, 5);
      case 0xaf -> new Res.Register(registers, registers.a(), 5);
      case 0xb0 -> new Res.Register(registers, registers.b(), 6);
      case 0xb1 -> new Res.Register(registers, registers.c(), 6);
      case 0xb2 -> new Res.Register(registers, registers.d(), 6);
      case 0xb3 -> new Res.Register(registers, registers.e(), 6);
      case 0xb4 -> new Res.Register(registers, registers.h(), 6);
      case 0xb5 -> new Res.Register(registers, registers.l(), 6);
      case 0xb6 -> new Res.Indirect(registers, 6);
      case 0xb7 -> new Res.Register(registers, registers.a(), 6);
      case 0xb8 -> new Res.Register(registers, registers.b(), 7);
      case 0xb9 -> new Res.Register(registers, registers.c(), 7);
      case 0xba -> new Res.Register(registers, registers.d(), 7);
      case 0xbb -> new Res.Register(registers, registers.e(), 7);
      case 0xbc -> new Res.Register(registers, registers.h(), 7);
      case 0xbd -> new Res.Register(registers, registers.l(), 7);
      case 0xbe -> new Res.Indirect(registers, 7);
      case 0xbf -> new Res.Register(registers, registers.a(), 7);
      case 0xc0 -> new Set.Register(registers, registers.b(), 0);
      case 0xc1 -> new Set.Register(registers, registers.c(), 0);
      case 0xc2 -> new Set.Register(registers, registers.d(), 0);
      case 0xc3 -> new Set.Register(registers, registers.e(), 0);
      case 0xc4 -> new Set.Register(registers, registers.h(), 0);
      case 0xc5 -> new Set.Register(registers, registers.l(), 0);
      case 0xc6 -> new Set.Indirect(registers, 0);
      case 0xc7 -> new Set.Register(registers, registers.a(), 0);
      case 0xc8 -> new Set.Register(registers, registers.b(), 1);
      case 0xc9 -> new Set.Register(registers, registers.c(), 1);
      case 0xca -> new Set.Register(registers, registers.d(), 1);
      case 0xcb -> new Set.Register(registers, registers.e(), 1);
      case 0xcc -> new Set.Register(registers, registers.h(), 1);
      case 0xcd -> new Set.Register(registers, registers.l(), 1);
      case 0xce -> new Set.Indirect(registers, 1);
      case 0xcf -> new Set.Register(registers, registers.a(), 1);
      case 0xd0 -> new Set.Register(registers, registers.b(), 2);
      case 0xd1 -> new Set.Register(registers, registers.c(), 2);
      case 0xd2 -> new Set.Register(registers, registers.d(), 2);
      case 0xd3 -> new Set.Register(registers, registers.e(), 2);
      case 0xd4 -> new Set.Register(registers, registers.h(), 2);
      case 0xd5 -> new Set.Register(registers, registers.l(), 2);
      case 0xd6 -> new Set.Indirect(registers, 2);
      case 0xd7 -> new Set.Register(registers, registers.a(), 2);
      case 0xd8 -> new Set.Register(registers, registers.b(), 3);
      case 0xd9 -> new Set.Register(registers, registers.c(), 3);
      case 0xda -> new Set.Register(registers, registers.d(), 3);
      case 0xdb -> new Set.Register(registers, registers.e(), 3);
      case 0xdc -> new Set.Register(registers, registers.h(), 3);
      case 0xdd -> new Set.Register(registers, registers.l(), 3);
      case 0xde -> new Set.Indirect(registers, 3);
      case 0xdf -> new Set.Register(registers, registers.a(), 3);
      case 0xe0 -> new Set.Register(registers, registers.b(), 4);
      case 0xe1 -> new Set.Register(registers, registers.c(), 4);
      case 0xe2 -> new Set.Register(registers, registers.d(), 4);
      case 0xe3 -> new Set.Register(registers, registers.e(), 4);
      case 0xe4 -> new Set.Register(registers, registers.h(), 4);
      case 0xe5 -> new Set.Register(registers, registers.l(), 4);
      case 0xe6 -> new Set.Indirect(registers, 4);
      case 0xe7 -> new Set.Register(registers, registers.a(), 4);
      case 0xe8 -> new Set.Register(registers, registers.b(), 5);
      case 0xe9 -> new Set.Register(registers, registers.c(), 5);
      case 0xea -> new Set.Register(registers, registers.d(), 5);
      case 0xeb -> new Set.Register(registers, registers.e(), 5);
      case 0xec -> new Set.Register(registers, registers.h(), 5);
      case 0xed -> new Set.Register(registers, registers.l(), 5);
      case 0xee -> new Set.Indirect(registers, 5);
      case 0xef -> new Set.Register(registers, registers.a(), 5);
      case 0xf0 -> new Set.Register(registers, registers.b(), 6);
      case 0xf1 -> new Set.Register(registers, registers.c(), 6);
      case 0xf2 -> new Set.Register(registers, registers.d(), 6);
      case 0xf3 -> new Set.Register(registers, registers.e(), 6);
      case 0xf4 -> new Set.Register(registers, registers.h(), 6);
      case 0xf5 -> new Set.Register(registers, registers.l(), 6);
      case 0xf6 -> new Set.Indirect(registers, 6);
      case 0xf7 -> new Set.Register(registers, registers.a(), 6);
      case 0xf8 -> new Set.Register(registers, registers.b(), 7);
      case 0xf9 -> new Set.Register(registers, registers.c(), 7);
      case 0xfa -> new Set.Register(registers, registers.d(), 7);
      case 0xfb -> new Set.Register(registers, registers.e(), 7);
      case 0xfc -> new Set.Register(registers, registers.h(), 7);
      case 0xfd -> new Set.Register(registers, registers.l(), 7);
      case 0xfe -> new Set.Indirect(registers, 7);
      case 0xff -> new Set.Register(registers, registers.a(), 7);
      default -> throw new InvalidOpcodeError((byte) 0xcb, registers.ir().get());
    };
  }
}
