#!/usr/bin/env python3

import json
import sys
from pprint import pprint


def get_operand_info(m, e):
  if m in ('jr', 'jp', 'ret', 'call'):
    if e['name'] in ('NC', 'NZ', 'C', 'Z'):
      return ('cond', 'Cond', f'Cond.{e["name"]}')
  if e['name'] == 'HL' and not e['immediate']:
    return ('r8', 'R8', 'R8.INDIRECT_HL')
  return {
    'A': ('r8', 'R8', 'R8.A'),
    'B': ('r8', 'R8', 'R8.B'),
    'C': ('r8', 'R8', 'R8.C'),
    'D': ('r8', 'R8', 'R8.D'),
    'E': ('r8', 'R8', 'R8.E'),
    'H': ('r8', 'R8', 'R8.H'),
    'L': ('r8', 'R8', 'R8.L'),
    'AF': ('r16', 'R16', 'R16.AF'),
    'BC': ('r16', 'R16', 'R16.BC'),
    'DE': ('r16', 'R16', 'R16.DE'),
    'HL': ('r16', 'R16', 'R16.HL'),
    'SP': ('r16', 'R16', 'R16.SP'),
    'a8': ('a8', None, None),
    'a16': ('a16', None, None),
    'e8': ('e8', None, None),
    'n16': ('n16', None, None),
    'n8': ('n8', None, None),
    '0': ('b3', 'int', '0'),
    '1': ('b3', 'int', '1'),
    '2': ('b3', 'int', '2'),
    '3': ('b3', 'int', '3'),
    '4': ('b3', 'int', '4'),
    '5': ('b3', 'int', '5'),
    '6': ('b3', 'int', '6'),
    '7': ('b3', 'int', '7'),
    '$00': ('tgt3', 'int', '0x00'),
    '$08': ('tgt3', 'int', '0x08'),
    '$10': ('tgt3', 'int', '0x10'),
    '$18': ('tgt3', 'int', '0x18'),
    '$20': ('tgt3', 'int', '0x20'),
    '$28': ('tgt3', 'int', '0x28'),
    '$30': ('tgt3', 'int', '0x30'),
    '$38': ('tgt3', 'int', '0x38'),
  }[e['name']]


def get_operand_kind(m, e):
  kind, _, _ = get_operand_info(m, e)
  prefix = ''
  if not e['immediate']:
    prefix += 'indirect_'
  if e.get('increment'):
    prefix += 'increment_'
  if e.get('decrement'):
    prefix += 'decrement_'
  return prefix + kind


def get_operand_type(m, e):
  _, type, _ = get_operand_info(m, e)
  if not type:
    return None
  return type


def get_operand(m, e):
  _, _, value = get_operand_info(m, e)
  if not value:
    return None
  suffix = ''
  if value == 'R16.HL':
    if e.get('increment'):
      suffix = 'I'
    if e.get('decrement'):
      suffix = 'D'
  return value + suffix


def get_name(d):
  m = d['mnemonic'].lower()
  parts = [m]
  for e in d['operands']:
    parts.append(get_operand_kind(m, e))
  return '_'.join(parts)


def get_operand_types(d):
  m = d['mnemonic'].lower()
  parts = []
  i = 0
  for e in d['operands']:
    part = get_operand_type(m, e)
    if not part:
      continue
    parts.append(f'{part} arg{i}')
    i += 1
  return ', '.join(parts)


def get_operands(d):
  m = d['mnemonic'].lower()
  parts = []
  for e in d['operands']:
    part = get_operand(m, e)
    if not part:
      continue
    parts.append(part)
  return ', '.join(parts)


def main(args):
  config = None
  with open('/Users/zacharyhirsch/Downloads/Opcodes.json') as f:
    config = json.load(f)

  print("// This file was generated by tools/gen_cpu_decoder.py")
  print("package com.zacharyhirsch.moldygameboy.emulator.cpu;")
  print()
  print("@javax.annotation.processing.Generated(\"tools/gen_cpu_decoder.py\")")
  print("interface CpuDecoder {")
  print()
  print("  enum R8 { B, C, D, E, H, L, INDIRECT_HL, A }")
  print("  enum R16 { AF, BC, DE, HL, SP, HLI, HLD }")
  print("  enum Cond { Z, NZ, C, NC }")

  instructions0 = {}
  for d in config['unprefixed'].values():
    instructions0[get_name(d)] = d
  instructions1 = {}
  for d in config['cbprefixed'].values():
    instructions1[get_name(d)] = d

  for name, d in sorted(instructions0.items()):
    print()
    print(f"  Cycle.Result {name}({get_operand_types(d)});")
  for name, d in sorted(instructions1.items()):
    print()
    print(f"  Cycle.Result {name}({get_operand_types(d)});")
  print()
  print("  default Cycle.Result decode(byte opcode) {")
  print("    return switch (Byte.toUnsignedInt(opcode)) {")
  for opcode, d in config['unprefixed'].items():
    name = get_name(d)
    # print(f"      case {opcode.lower()} -> {{")
    # print(f"        System.out.println(\"{opcode.lower()} {name} {get_operands(d)}\");")
    # print(f"        yield {name}({get_operands(d)});")
    # print(f"      }}")
    print(f"      case {opcode.lower()} -> {name}({get_operands(d)});")
  print("      default -> throw new IllegalArgumentException();")
  print("    };")
  print("  }")
  print()
  print("  default Cycle.Result decode2(byte opcode) {")
  print("    return switch (Byte.toUnsignedInt(opcode)) {")
  for opcode, d in config['cbprefixed'].items():
    name = get_name(d)
    # print(f"      case {opcode.lower()} -> {{")
    # print(f"        System.out.println(\"{opcode.lower()} {name} {get_operands(d)}\");")
    # print(f"        yield {name}({get_operands(d)});")
    # print(f"      }}")
    print(f"      case {opcode.lower()} -> {name}({get_operands(d)});")
  print("      default -> throw new IllegalArgumentException();")
  print("    };")
  print("  }")
  print("}")


if __name__ == '__main__':
  sys.exit(main(sys.argv[1:]))
